"use client";
import { frequencyInfo } from "@/lib/scheduleStorage";
import type { ExtractedHEP } from "@/types/schedule";
import type { ReviewExercise } from "@/lib/hepReview";
export default function HEPExerciseEditor({ original, review, onChange, disabled }: { original: ExtractedHEP; review: ReviewExercise[]; onChange: (items: ReviewExercise[]) => void; disabled: boolean }) {
  const input = "mt-1.5 w-full rounded-lg border-[1.5px] border-[#C4CFCC] bg-white/70 px-3 py-2 text-[17px] text-[#1F2A33] outline-none focus:border-[#3F6E47] focus:ring-3 focus:ring-[#3F6E47]/25";
  return <section id="hep-review" tabIndex={-1} className="mx-auto mt-12 max-w-5xl scroll-mt-8"><h2 className="font-display text-[clamp(32px,4vw,50px)] font-extrabold leading-none tracking-tight">Check your plan</h2><p className="mt-3 max-w-[62ch] text-[17px] leading-snug opacity-90">A booklet may contain exercises that were not assigned to you. Nothing is selected automatically. Include only exercises from your actual therapist-provided plan. Copy any corrections from that plan; leave unspecified values blank.</p><p className="mt-3 text-[16px]"><span className="rv-hl px-1.5 text-[#1F2A33]">Highlighted</span> fields weren&apos;t on the sheet or couldn&apos;t be read. The reader can make mistakes, so compare every entry you include with your paper copy.</p><p aria-live="polite" className="mt-4 font-display text-xl font-bold text-[#F2C14E]">{review.filter(item => item.included).length} of {review.length} included</p><div className="mt-5 space-y-4">{review.map((item, index) => {
    const update = (patch: Partial<ReviewExercise["exercise"]>) => onChange(review.map((row, i) => i === index ? { ...row, exercise: { ...row.exercise, ...patch } } : row));
    return <fieldset disabled={disabled} key={index} className={`rounded-[22px] border-l-[6px] bg-[#EEF2F1] p-5 text-[#1F2A33] shadow-lg transition ${item.included ? "border-[#3F6E47]" : "border-[#C4CFCC] opacity-75"}`}><legend className="sr-only">Exercise {index + 1}</legend><p aria-hidden className="font-display text-[15px] font-bold text-[#4F5D68]">Exercise {index + 1}</p><label className="mt-1 flex w-fit cursor-pointer items-center gap-3 rounded-full border-2 border-[#1F2A33] px-4 py-2 font-display font-semibold"><input type="checkbox" checked={item.included} onChange={e => onChange(review.map((row, i) => i === index ? { ...row, included: e.target.checked } : row))} className="h-5 w-5 accent-[#3F6E47]" />Included in my plan: {item.included ? "Yes" : "No"}</label><label className="mt-4 block text-[15px] text-[#4F5D68]">Exercise name<input className={`${input} font-display text-[22px] font-bold`} value={item.exercise.name} onChange={e => update({ name: e.target.value })} /></label><div className="mt-4 grid gap-4 sm:grid-cols-3">{([['sets', 'Sets'], ['repetitions', 'Reps'], ['holdSeconds', 'Hold (seconds)']] as const).map(([key, label]) => <label key={key} className="text-[15px] text-[#4F5D68]">{label}<input type="number" min={key === 'holdSeconds' ? .1 : 1} step={key === 'holdSeconds' ? 'any' : 1} placeholder="Not specified" className={`${input} font-bold ${item.included && key !== 'holdSeconds' && item.exercise[key] == null ? 'rv-hl' : ''}`} value={item.exercise[key] ?? ''} onChange={e => update({ [key]: e.target.value === '' ? null : Number(e.target.value) })} /></label>)}</div><label className="mt-4 block text-[15px] text-[#4F5D68]">Your PT&apos;s instructions<textarea rows={3} className={input} value={item.exercise.instructions ?? ''} onChange={e => update({ instructions: e.target.value })} /></label>{item.exercise.notes && <p className="mt-3 whitespace-pre-wrap text-[15px] text-[#4F5D68]">Original notes: {item.exercise.notes}</p>}<details className="mt-4 text-sm text-slate-400"><summary className="cursor-pointer">Original extracted entry</summary><pre className="mt-3 whitespace-pre-wrap font-sans">{JSON.stringify(original.exercises[index], null, 2)}</pre></details></fieldset>;
  })}</div><details className="rv-glass mt-5 rounded-2xl p-4 text-[15px]"><summary className="cursor-pointer">Original plan instructions and extraction notes</summary><p className="mt-3">Frequency: {frequencyInfo(original.frequency).instruction}</p><p className="mt-3 whitespace-pre-wrap">{[original.frequency.rawText, ...original.generalInstructions, ...original.extractionNotes].filter(Boolean).join('\n\n') || 'No additional instructions extracted.'}</p></details></section>;
}
