"use client";
import { frequencyInfo } from "@/lib/scheduleStorage";
import type { ExtractedHEP } from "@/types/schedule";
import type { ReviewExercise } from "@/lib/hepReview";
export default function HEPExerciseEditor({ original, review, onChange, disabled }: { original: ExtractedHEP; review: ReviewExercise[]; onChange: (items: ReviewExercise[]) => void; disabled: boolean }) {
  const input = "mt-2 w-full rounded-xl border border-white/20 bg-slate-950 px-3 py-2 text-white";
  return <section id="hep-review" tabIndex={-1} className="mx-auto mt-12 max-w-5xl scroll-mt-8"><h2 className="text-2xl font-bold">Choose and verify your HEP exercises</h2><p className="mt-3 text-sm leading-6 text-slate-300">A booklet may contain exercises that were not assigned to you. Nothing is selected automatically. Include only exercises from your actual therapist-provided plan. Copy any corrections from that plan; leave unspecified values blank.</p><p className="mt-3 text-sm text-amber-200">AI extraction may make mistakes. Compare every selected entry with your original HEP.</p><p aria-live="polite" className="mt-4 text-cyan-200">{review.filter(item => item.included).length} selected</p><div className="mt-5 space-y-4">{review.map((item, index) => {
    const update = (patch: Partial<ReviewExercise["exercise"]>) => onChange(review.map((row, i) => i === index ? { ...row, exercise: { ...row.exercise, ...patch } } : row));
    return <fieldset disabled={disabled} key={index} className={`rounded-2xl border p-5 ${item.included ? "border-cyan-300/40 bg-indigo-400/10" : "border-white/10 bg-white/5"}`}><legend className="px-2 text-sm">Exercise {index + 1}</legend><label className="flex cursor-pointer items-center gap-3 font-semibold"><input type="checkbox" checked={item.included} onChange={e => onChange(review.map((row, i) => i === index ? { ...row, included: e.target.checked } : row))} className="h-5 w-5 accent-cyan-300" />Included in my HEP: {item.included ? "Yes" : "No"}</label><label className="mt-4 block text-sm">Exercise name<input className={input} value={item.exercise.name} onChange={e => update({ name: e.target.value })} /></label><div className="mt-4 grid gap-4 sm:grid-cols-3">{([['sets', 'Sets'], ['repetitions', 'Reps'], ['holdSeconds', 'Hold (seconds)']] as const).map(([key, label]) => <label key={key} className="text-sm">{label}<input type="number" min={key === 'holdSeconds' ? .1 : 1} step={key === 'holdSeconds' ? 'any' : 1} placeholder="Not specified" className={input} value={item.exercise[key] ?? ''} onChange={e => update({ [key]: e.target.value === '' ? null : Number(e.target.value) })} /></label>)}</div><label className="mt-4 block text-sm">Instructions<textarea rows={3} className={input} value={item.exercise.instructions ?? ''} onChange={e => update({ instructions: e.target.value })} /></label>{item.exercise.notes && <p className="mt-3 whitespace-pre-wrap text-sm text-amber-100">Original notes: {item.exercise.notes}</p>}<details className="mt-4 text-sm text-slate-400"><summary className="cursor-pointer">Original extracted entry</summary><pre className="mt-3 whitespace-pre-wrap font-sans">{JSON.stringify(original.exercises[index], null, 2)}</pre></details></fieldset>;
  })}</div><details className="mt-5 rounded-xl border border-white/10 p-4 text-sm text-slate-300"><summary className="cursor-pointer">Original plan instructions and extraction notes</summary><p className="mt-3">Frequency: {frequencyInfo(original.frequency).instruction}</p><p className="mt-3 whitespace-pre-wrap">{[original.frequency.rawText, ...original.generalInstructions, ...original.extractionNotes].filter(Boolean).join('\n\n') || 'No additional instructions extracted.'}</p></details></section>;
}
